package com.noghre.sod.di

import android.content.Context
import com.noghre.sod.core.network.CertificatePinningConfig
import com.noghre.sod.core.network.RetryInterceptor
import com.noghre.sod.core.security.NativeKeys
import dagger.Module
import dagger.Provides
import dagger.hilt.InstallIn
import dagger.hilt.android.qualifiers.ApplicationContext
import dagger.hilt.components.SingletonComponent
import okhttp3.OkHttpClient
import okhttp3.logging.HttpLoggingInterceptor
import retrofit2.Retrofit
import retrofit2.converter.gson.GsonConverterFactory
import java.util.concurrent.TimeUnit
import javax.inject.Singleton

/**
 * Network dependency injection module.
 * Provides OkHttp client with security, retry, and timeout configurations.
 */
@Module
@InstallIn(SingletonComponent::class)
object NetworkModule {

    private const val CONNECT_TIMEOUT_SECONDS = 30L
    private const val READ_TIMEOUT_SECONDS = 30L
    private const val WRITE_TIMEOUT_SECONDS = 30L
    private const val CALL_TIMEOUT_SECONDS = 60L

    /**
     * Provide configured OkHttpClient with:
     * - Certificate pinning
     * - Retry mechanism with exponential backoff
     * - Timeout configurations
     * - HTTP logging (debug only)
     */
    @Provides
    @Singleton
    fun provideOkHttpClient(
        @ApplicationContext context: Context
    ): OkHttpClient {
        val builder = OkHttpClient.Builder()

        // Timeouts (Network Issue #3.3)
        builder
            .connectTimeout(CONNECT_TIMEOUT_SECONDS, TimeUnit.SECONDS)
            .readTimeout(READ_TIMEOUT_SECONDS, TimeUnit.SECONDS)
            .writeTimeout(WRITE_TIMEOUT_SECONDS, TimeUnit.SECONDS)
            .callTimeout(CALL_TIMEOUT_SECONDS, TimeUnit.SECONDS)

        // Certificate pinning (Security Issue #1.2)
        builder.certificatePinner(CertificatePinningConfig.createCertificatePinner())

        // Retry mechanism (Network Issue #3.2)
        builder.addInterceptor(RetryInterceptor(maxRetries = 3, initialDelayMs = 1000))

        // HTTP logging interceptor (debug only)
        val loggingInterceptor = HttpLoggingInterceptor().apply {
            level = if (BuildConfig.DEBUG) {
                HttpLoggingInterceptor.Level.BODY
            } else {
                HttpLoggingInterceptor.Level.NONE
            }
        }
        builder.addInterceptor(loggingInterceptor)

        return builder.build()
    }

    /**
     * Provide Retrofit instance with:
     * - Custom OkHttp client
     * - Gson converter
     * - API base URL from native library
     */
    @Provides
    @Singleton
    fun provideRetrofit(
        okHttpClient: OkHttpClient
    ): Retrofit {
        val baseUrl = try {
            NativeKeys.getApiUrl()
        } catch (e: Exception) {
            "https://api.noghresod.ir/v1/" // Fallback
        }

        return Retrofit.Builder()
            .baseUrl(baseUrl)
            .client(okHttpClient)
            .addConverterFactory(GsonConverterFactory.create())
            .build()
    }
}

/**
 * Build configuration (auto-generated by Gradle)
 */
object BuildConfig {
    val DEBUG = BuildConfig.DEBUG
}