package com.noghre.sod.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF2E807F)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFB1F1ED)
val md_theme_light_onPrimaryContainer = Color(0xFF002626)
val md_theme_light_secondary = Color(0xFF4B635E)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFCEE9E2)
val md_theme_light_onSecondaryContainer = Color(0xFF07201B)
val md_theme_light_tertiary = Color(0xFF56577E)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFDBDEFF)
val md_theme_light_onTertiaryContainer = Color(0xFF0F1237)
val md_theme_light_error = Color(0xFFB3261E)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_errorContainer = Color(0xFFF9DEDC)
val md_theme_light_onErrorContainer = Color(0xFF410E0B)
val md_theme_light_background = Color(0xFFFBFDFC)
val md_theme_light_onBackground = Color(0xFF191C1B)
val md_theme_light_surface = Color(0xFFFBFDFC)
val md_theme_light_onSurface = Color(0xFF191C1B)

val md_theme_dark_primary = Color(0xFF99D8D5)
val md_theme_dark_onPrimary = Color(0xFF003F3E)
val md_theme_dark_primaryContainer = Color(0xFF145957)
val md_theme_dark_onPrimaryContainer = Color(0xFFB1F1ED)
val md_theme_dark_secondary = Color(0xFFB2CCC6)
val md_theme_dark_onSecondary = Color(0xFF1E3531)
val md_theme_dark_secondaryContainer = Color(0xFF334C46)
val md_theme_dark_onSecondaryContainer = Color(0xFFCEE9E2)
val md_theme_dark_tertiary = Color(0xFFC0C3FF)
val md_theme_dark_onTertiary = Color(0xFF252750)
val md_theme_dark_tertiaryContainer = Color(0xFF3D3E67)
val md_theme_dark_onTertiaryContainer = Color(0xFFDBDEFF)
val md_theme_dark_error = Color(0xFFF2B8B5)
val md_theme_dark_onError = Color(0xFF601410)
val md_theme_dark_errorContainer = Color(0xFF8C1D18)
val md_theme_dark_onErrorContainer = Color(0xFFF9DEDC)
val md_theme_dark_background = Color(0xFF191C1B)
val md_theme_dark_onBackground = Color(0xFFE1E3E2)
val md_theme_dark_surface = Color(0xFF191C1B)
val md_theme_dark_onSurface = Color(0xFFE1E3E2)
